// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJgEzRq2d51PmFZA4ezHukGwS11yP6_Q8',
    appId: '1:67086622359:web:766ddd3b707734061093d2',
    messagingSenderId: '67086622359',
    projectId: 'kerala2024-e2d53',
    authDomain: 'kerala2024-e2d53.firebaseapp.com',
    databaseURL: 'https://kerala2024-e2d53-default-rtdb.firebaseio.com',
    storageBucket: 'kerala2024-e2d53.appspot.com',
    measurementId: 'G-ZLPKMKS8PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiUwsmG-W5jDXLJ_ijDx2gzcwP3ntHwrE',
    appId: '1:67086622359:android:ebb9f6af89a675781093d2',
    messagingSenderId: '67086622359',
    projectId: 'kerala2024-e2d53',
    databaseURL: 'https://kerala2024-e2d53-default-rtdb.firebaseio.com',
    storageBucket: 'kerala2024-e2d53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBukJJYc0OMOdVVnx4bo-mqv14YB6A6W5s',
    appId: '1:67086622359:ios:62f9392b77edf2db1093d2',
    messagingSenderId: '67086622359',
    projectId: 'kerala2024-e2d53',
    databaseURL: 'https://kerala2024-e2d53-default-rtdb.firebaseio.com',
    storageBucket: 'kerala2024-e2d53.appspot.com',
    iosBundleId: 'com.example.kLottery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBukJJYc0OMOdVVnx4bo-mqv14YB6A6W5s',
    appId: '1:67086622359:ios:62f9392b77edf2db1093d2',
    messagingSenderId: '67086622359',
    projectId: 'kerala2024-e2d53',
    databaseURL: 'https://kerala2024-e2d53-default-rtdb.firebaseio.com',
    storageBucket: 'kerala2024-e2d53.appspot.com',
    iosBundleId: 'com.example.kLottery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPFpFusOIrsB6F1WlMei177vGo0GkGSUg',
    appId: '1:67086622359:web:943b0c10d6ca665b1093d2',
    messagingSenderId: '67086622359',
    projectId: 'kerala2024-e2d53',
    authDomain: 'kerala2024-e2d53.firebaseapp.com',
    databaseURL: 'https://kerala2024-e2d53-default-rtdb.firebaseio.com',
    storageBucket: 'kerala2024-e2d53.appspot.com',
    measurementId: 'G-X35419K29S',
  );
}
